name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  testing-php-laravel-combinations:
    runs-on: ubuntu-latest
    matrix:
      laravel-version: ['8', '9']
      php-version: ['7.4', '8.0', '8.1', '8.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: shivammathur/setup-php@v2
        with:
          php-version: {{ matrix.php-version}}
          coverage: xdebug
          extensions: sqlite3, pdo_sqlite
          tools: composer, phpunit
#      - name: Set testbench dependency
#        run: composer require orchestra/testbench "^6"
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-testing-php${{ matrix.php-version }}-laravel${{ matrix.laravel-version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Composer
        run: composer install
      - name: Run Tests
        run: composer run test-coverage
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: php-cs-fixer
      - name: Run Lint Check
        run: php-cs-fixer fix --dry-run -vv --diff --config=.php_cs.dist.php
  phan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: phan
      - name: Run Static Analysis
        run: phan --progress-bar -o phan_analysis.txt
