name: CI

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: php-actions/composer@v6
        with:
          version: 2
          php_version: 8.0
          progress: yes
          dev: yes
      - name: Test
        uses: php-actions/phpunit@v3
        with:
          php_version: 8
          configuration: /phpunit.xml
