name: CI

on:
  push:
    branches:
      - 3.2.x-with-mutation-testing
      - mutation-testing-pr
  pull_request:
    branches:
      - main
      - 3.2.x-with-mutation-testing

jobs:
  testing-php-laravel-combinations:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        laravel-version: ['^8.0', '^9.0']
        php-version: ['7.4', '8.0', '8.1', '8.2']
        exclude:
          - laravel-version: '^8.0'
            php-version: '8.2'
          - laravel-version: '^9.0'
            php-version: '7.4'
    name: Test with PHP ${{ matrix.php-version }}, Laravel ${{ matrix.laravel-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
          extensions: sqlite3, pdo_sqlite
          tools: composer, phpunit
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-testing-php${{ matrix.php-version }}-laravel${{ matrix.laravel-version }}-${{ hashFiles('**/composer.json') }}
      - name: Require Laravel
        run: composer require laravel/framework ${{ matrix.laravel-version }} --no-interaction
      - name: Run Tests
        run: vendor/bin/phpunit --coverage-text

  mutation-testing:
    name: Mutation Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: pcov
          extensions: sqlite3, pdo_sqlite
          tools: composer, phpunit
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-testing-php8.2-laravel^9.0-${{ hashFiles('**/composer.json') }}
      - name: Require Laravel
        run: composer require laravel/framework ^9.0 --no-interaction
      - name: Run Tests
        run: vendor/bin/phpunit --coverage-text --coverage-xml=coverage.xml --log-junit=junit.xml
      - name: Install Mutation Testing Package
        run: composer config --no-plugins allow-plugins.infection/extension-installer true && composer require --dev infection/infection
      - name: Full Mutation Testing
        if: github.event_name == 'push'
        run: vendor/bin/infection -j$(nproc) --coverage=. --min-msi=70 --min-covered-msi=70 >> $GITHUB_STEP_SUMMARY
      - name: PR Mutation Testing
        if: github.event_name == 'pull_request'
        run: vendor/bin/infection -j$(nproc) --coverage=. --min-msi=70 --min-covered-msi=70 --git-diff-filter=AM >> $GITHUB_STEP_SUMMARY

  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: php-cs-fixer
      - name: Run Lint Check
        run: php-cs-fixer fix --dry-run -vv --diff --config=.php_cs.dist.php
  phan:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: phan
      - name: Run Static Analysis
        run: phan --progress-bar -o phan_analysis.txt
