name: CI

on: [push]

jobs:
  testing-8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install Dependencies
        uses: php-actions/composer@v6
        with:
          version: 2
          php_version: 8.0
          progress: yes
          dev: yes
      - name: Test PHP 8
        uses: php-actions/phpunit@v3
        with:
          php_version: 8
          configuration: phpunit.xml
  testing-74:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install Dependencies
        uses: php-actions/composer@v6
        with:
          version: 2
          php_version: 8.0
          progress: yes
          dev: yes
      - name: Test PHP 7.4
        uses: php-actions/phpunit@v3
        with:
          php_version: 7.4
          configuration: phpunit.xml
